### ISSUE TITLE
toHalf . fromHalf /= id  for some NaN values

### ISSUE THREAD

**Issue by dcoutts** [ekmett/half#3]
```
> let roundTrip w = (getHalf . toHalf . fromHalf . Half $ w) == w
> roundTrip 0x7e00
True
> roundTrip 0x7f00
True
> roundTrip 0x7d00
False
```

**Comment by dcoutts** [comment]
Or more generally:

```
> let roundTrip w = (getHalf . toHalf . fromHalf . Half $ w) == w
> all isNaN  [ Half w | w <- [minBound..maxBound], not (roundTrip w) ]
True
> length [ Half w | w <- [minBound..maxBound], not (roundTrip w) ]
1022
```

**Comment by ekmett** [comment]
We don't make an effort to preserve NaN bits when doing any other floating point conversions, so this one seems to be a bit artificial as issues go.

**Comment by ekmett** [comment]
I'd happily take a patch that provided this property. There are just a few lines in the `cbits` that would need to change but they are fiddly and would require testing.

**Comment by basile-henry** [comment]
I know this issue is old, but I have recently encountered an odd behaviour for `Half` that might be related to this issue. (I can open a separate issue if you think it is not related enough).

The issue has to do with the `Ord` instance for `Half` that behaves differently from the `Float` one when using a `NaN` value:

```haskell
λ > QNaN > QNaN
True
λ > QNaN < QNaN
False
```

(Same behavior with `SNaN` and a mix of `QNaN` and `SNaN`)

For comparison with a `Float` (using NaN from the [ieee754 package](https://hackage.haskell.org/package/ieee754)):

```haskell
λ > (nan :: Float) > nan
False
λ > (nan :: Float) < nan
False
```

This breaks some of my testing. I can ignore `NaN` values for the moment but I think it would be better to fix this issue. While it might not be worth preserving the exact bit pattern of a `NaN`, keeping a coherent `Ord` instance seems pretty important to me.

I can try to tackle this issue myself if you want. It would be great if I could get some pointers though. 

Which reference documentation was used for Half? Something from ieee?

What kind of test would be needed? Would a few simple property tests like `Ord` and `roundTrip` be enough?

**Comment by ekmett** [comment]
We should fix the comparison to be IEEE compliant, definitely. As for documentation, I more or less borrowed everythig from the OpenGL shader spec. I know IEEE was sniffing around a standard, but I don't know if it ever happened.

**Comment by ekmett** [comment]
re the original problem here, we can't preserve _all_ the NaN bits, when going the other direction, obviously, there just isn't room,  just the first few of them, and ghc itself mangles the signaling bit on regular floats, so at least the distinction between SNaN and QNaN will necessarily be lost. We'll want to treat the signaling bit the same way GHC does.

**Comment by ekmett** [comment]
The compare should probably be a separate issue though, as it is readily fixed without fixing all NaNs. In fact it is ever so slightly easier to fix if we don't fix all NaNs. :)

**Comment by basile-henry** [comment]
Actually, I have just realised there is a really easy fix for `Ord`, which is to use more than the minimal definition:

```haskell
instance Ord Half where
  compare = compare `on` fromHalf
  (<) = (<) `on` fromHalf
  (<=) = (<=) `on` fromHalf
  (>) = (>) `on` fromHalf
  (>=) = (>=) `on` fromHalf
```

Would you like me to make a pull request for this along with a couple of tests? Should I create a separate issue for this now that I understand that the `Ord` instance does not rely on a proper implementation of `NaN` in order to have the same behavior as `Float`?

**Comment by ekmett** [comment]
On HEAD:

```
Prelude Numeric.Half> all roundTrip [minBound..maxBound]
True
```
